### ISSUE TITLE
Pass custom values to to generate names.

### ISSUE THREAD

**Issue by sbstjn** [sbstjn/serverless-dynamodb-autoscaling#14]
When you have a fancy ( aka broken? ) `serverless.yml` the auto-generated names will fail to create unique names. The service name should be part of the generated names.

```yaml
service: ${self:custom.service}

provider:
  stage: v1

custom:
  fallback:
    env: dev

  name: api
  env: ${opt:env, self:custom.fallback.env}
  service: ${self:custom.env}-${self:custom.name}
```
