### ISSUE TITLE
Apply same settings to global secondary indexes

### ISSUE THREAD

**Issue by yosriady** [sbstjn/serverless-dynamodb-autoscaling#2]
![screen shot 2017-07-20 at 1 41 34 pm](https://user-images.githubusercontent.com/1084226/28402222-3ab0ecf8-6d51-11e7-9383-ba07a9f7e83b.png)

What do you think of adding support for the ability to 'Apply same settings to global secondary indexes'?

**Comment by sbstjn** [comment]
Sure, would make sense to support this well. Hopefully I can find the time to look at the [CloudFormation docs](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.CLI.html) in the next days. But you are always welcome to provide a pull request :)

**Comment by sbstjn** [comment]
Have you checked the docs for this topic? I just had a quick look and found nothing about applying the settings to all index. Anyway, the target template has a `ResourceId`, which is per default `table/${tablename}` and should easily be extended to indexes.

**Comment by yosriady** [comment]
Hmm right there might not be official CF support for this yet, so perhaps we can wait for it for now.

Otherwise, we will need to add the Autoscaling resources (`Policy`, `Role`, `Target`) to each table Index manually.

**Comment by sbstjn** [comment]
I think we could easily add this feature by updating the configuration syntax and offer a `table` and `index` property:

### Table
```yaml
custom:
  capacities:
    - table: custom-table  # DynamoDB table name
      read:
        minimum: 5        # Minimum read capacity
        maximum: 1000     # Maximum read capacity
        usage: 0.75       # Targeted usage percentage
      write:
        minimum: 40       # Minimum write capacity
        maximum: 200      # Maximum write capacity
        usage: 0.5        # Targeted usage percentage
```

### Index
```yaml
custom:
  capacities:
    - index: custom-index  # DynamoDB index name
      read:
        minimum: 5        # Minimum read capacity
        maximum: 1000     # Maximum read capacity
        usage: 0.75       # Targeted usage percentage
      write:
        minimum: 40       # Minimum write capacity
        maximum: 200      # Maximum write capacity
        usage: 0.5        # Targeted usage percentage
```
