### ISSUE TITLE
Error when re-deploying

### ISSUE THREAD

**Issue by TimMensch** [sbstjn/serverless-dynamodb-autoscaling#32]
I'm seeing this error on deploy:

>  An error occurred: myapiAutoScalingTargetWrite7b99aba1d7be2b722192793defb4676 - table/my-api-alpha-checkin|dynamodb:table:WriteCapacityUnits|dynamodb already exists.

Considering re-deploying is how I've been testing, this is a problem. Worse, just *deleting* the table doesn't help. So for now I've had to disable `serverless-dynamodb-autoscaling` so that I can deploy at all.

Thoughts?

**Comment by TimMensch** [comment]
Further information: It just doesn't seem to work for me at all. I did a completely clean deploy and it still failed.

I'm trying to create and autoscale four DynamoDB tables. Here are some relevant `serverless.yml` excerpts from the table that failed *first* (though they all failed):

```yaml
    capacities:
      - table: TagDynamoDbTable
      read:
        minimum: 5       # Minimum read capacity
        maximum: 1000    # Maximum read capacity
        usage: 0.75      # Targeted usage percentage
      write:
        minimum: 5       # Minimum write capacity
        maximum: 1000    # Maximum write capacity
        usage: 0.75      # Targeted usage percentage
```

The Dynamo Table:

```yaml
    TagDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: mac
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: mac
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 1000
        StreamSpecification:
            StreamViewType: "NEW_IMAGE"
        TableName: ${self:provider.environment.DYNAMODB_TAG_TABLE}
```

And the error:

```
  An error occurred: myapiAutoScalingTargetReadTagDynamoDbTableAlphaUswest1 - table/my-api-alpha-tag|dynamodb:table:ReadCapacityUnits|dynamodb already exists.                           
``

This is after the CloudFormation template was completely deleted and re-created.
