### ISSUE TITLE
Get table name from Resources

### ISSUE THREAD

**Issue by dbeja** [sbstjn/serverless-dynamodb-autoscaling#37]
Hi,

I'm trying to get the table name from Resources section with Ref but doesn't work.

I have this configuration in serverless.yml:

```
custom:
  capacities:
    - table: { Ref: tblUser }
      read:
        minimum: 5
        maximum: 1000
      write:
        minimum: 5
        maximum: 500

resources:
  Resources:
    tblUser:
...
```

And when I deploy I get this error:

```
Serverless: Configure DynamoDB Auto Scaling …
Serverless:  - Building configuration for resource "table/[object Object]"
Serverless: Skipping DynamoDB Auto Scaling: data.charAt is not a function!
```

Thanks!
