### ISSUE TITLE
The CloudFormation template is invalid: Template format error: Resource name DynamoDBAutoscaleRoletable_with_underscore is non alphanumeric.

### ISSUE THREAD

**Issue by charleswhchan** [sbstjn/serverless-dynamodb-autoscaling#4]
Tried using the plugin but ran into the following error:
> The CloudFormation template is invalid: Template format error: Resource name DynamoDBAutoscaleRolemy_table_dev is non alphanumeric.

This is my serverless.yml file:
```
plugins:
  - serverless-dynamodb-autoscaling

custom:
  capacities:
    - name: my_table_dev
      read:
        minimum: 1
        maximum: 100
        usage: 0.70
      write:
        minimum: 1
        maximum: 100
        usage: 0.70
```

If I add the autoscaling via the AWS Console, it will default to creating a "DynamoDBAutoScaleRole" or use an existing role:
![image](https://user-images.githubusercontent.com/679475/28427519-525402c6-6d2b-11e7-9f21-155ab96b0181.png)

Perhaps the easiest solution is to strip the underscore from the table name (if any) to create a valid resource name? What do you think?
