### ISSUE TITLE
Is it possible to set different capacities for table and index ?

### ISSUE THREAD

**Issue by manjirinamjoshi** [sbstjn/serverless-dynamodb-autoscaling#46]
Hello,

Wondering if it is possible to set different values of read: minimum (capacities) for table and global secondary index ?

For e.g. 
capacities:
    - table: TestTable  # DynamoDB Resource
      index:              # List or single index name
        - test1-index
        - test2-index
      read:
        minimum: 20 # Minimum read capacity
        maximum: 100     # Maximum read capacity
        usage: 0.70       # Targeted usage percentage
      write:
        minimum: 5       # Minimum write capacity
        maximum: 40      # Maximum write capacity
        usage: 0.7 

I would like a different minimum read capacity for table. And, a different value for test1-index

If it is possible, then could you please show an example.

Thank you

Sincerely,
Manjiri

**Comment by manjirinamjoshi** [comment]
Dont think AWS allows to set different values for table and index. But, still keeping the issue open, incase it is possible

**Comment by l-j-g** [comment]
Hi - 
I believe you can set the minimum provisioned read/write (non-scaling) in the resources section i.e :

```
           - IndexName: MarketCapIndex
              KeySchema:
                - AttributeName: GSI1PK
                  KeyType: HASH
                - AttributeName: Market Cap
                  KeyType: RANGE
              Projection:
                ProjectionType: ALL
              ProvisionedThroughput:
                ReadCapacityUnits: 2
                WriteCapacityUnits: 2
   ```             
As a side note i recently had the experience of my dynamodb going into meltdown because the provisioned writes were not matched between the main table and the index. This can cause the write to fail, and the function to restart - in my cause it was a db initialization function which then started and failed over and over again. 

 AWS recommend, **For best performance, be sure to turn on Use the same read/write capacity settings for all global secondary indexes**

More on this here: https://aws.amazon.com/premiumsupport/knowledge-center/dynamodb-gsi-throttling-table/
