### ISSUE TITLE
'roleName' failed to satisfy constraint: Member must have length less than or equal to 64

### ISSUE THREAD

**Issue by charleswhchan** [sbstjn/serverless-dynamodb-autoscaling#9]
serverless.yml:
```
plugins:
  - serverless-dynamodb-autoscaling

custom:
  capacities:
    - table: subscriptionsTable
      index:
        - SubscriptionsUserIdIndex
      read:
        minimum: 1
        maximum: 100
        usage: 0.7
      write:
        minimum: 1
        maximum: 100
        usage: 0.7
```

output:
```
  Serverless Error ---------------------------------------

  An error occurred while provisioning your stack: DynamoDBAutoscaleRolesubscriptionsTableSubscriptionsUserIdIndexdev - 1 validation error detected: Value 'DynamoDBAutoscaleRolesubscriptionsTableSubscriptionsUserIdIndexdev' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64.
```

I think the error is indicating the role name must be <=64 characters. When the role name is generated, is there a way to shorten it? Or use the existing `DynamoDBAutoscaleRole`?
